server:
  port: 8080
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka-service-service:8761/eureka/
    instance:
        preferIpAddress: true
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
        default-filters:
          - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            exposedHeaders: "*"
            allowCredentials: true
      routes:
        - id: user-services
          uri: lb://microServicio-User
          predicates:
            - Path=/prestabanco/user/**
        - id: credit-services
          uri: lb://microServicio-credito
          predicates:
            - Path=/prestabanco/credito/**
        - id: evaluacion-services
          uri: lb://microServicio-Evaluacion
          predicates:
            - Path=/prestabanco/evaluacion/**
        - id: seguimiento-services
          uri: lb://microServicio-seguimiento
          predicates:
            - Path=/prestabanco/seguimiento/**
        - id: solicitud-services
          uri: lb://microServicio-solicitud
          predicates:
            - Path=/prestabanco/solicitud/**, /prestabanco/sc/**
