server:
  port: ${PORT:${SERVER_PORT:0}}
spring:
  datasource:
    url: jdbc:postgresql://microservicio-solicitud-db-service:5432/microServicio-solicitud-db
    username: postgres
    password: 12345
  jpa:
    hibernate:
      ddl-auto: update
eureka:
  instance:
    preferIpAddress: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka-service-service:8761/eureka/