server:
  port: ${PORT:${SERVER_PORT:0}}
spring:
  datasource:
    url: jdbc:postgresql://microservicio-evaluacion-db-service:5434/microServicio-evaluacion-bd
    username: postgres
    password: 12345
  jpa:
    hibernate:
      ddl-auto: update
eureka:
  instance:
    preferIpAddress: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka